services:
  - type: web
    name: roadmap-saas-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: roadmap-saas-backend
          property: port
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true

